import 'package:renatus/Models/statemodel.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddFundInpurModelCompanyBanks {
/*
{
  "CBId": "4",
  "Bank": "Bandhan Bank",
  "Branch": "DALHOUSIE",
  "Accno": "10190000882112",
  "IFSC": "BDBL0001625",
  "City": "Kolkata",
  "State": "West Bengal",
  "StateId": "35",
  "CBStatus": "0",
  "UpdatedOn": "31 Mar 2021",
  "UpdatedBy": "admin - USER001",
  "BankImage": "",
  "Msg": "SUCCESS"
}
*/

  String? CBId;
  String? Bank;
  String? Branch;
  String? Accno;
  String? IFSC;
  String? City;
  String? State;
  String? StateId;
  String? CBStatus;
  String? UpdatedOn;
  String? UpdatedBy;
  String? BankImage;
  String? Msg;

  AddFundInpurModelCompanyBanks({
    this.CBId,
    this.Bank,
    this.Branch,
    this.Accno,
    this.IFSC,
    this.City,
    this.State,
    this.StateId,
    this.CBStatus,
    this.UpdatedOn,
    this.UpdatedBy,
    this.BankImage,
    this.Msg,
  });
  AddFundInpurModelCompanyBanks.fromJson(Map<String, dynamic> json) {
    CBId = json['CBId']?.toString();
    Bank = json['Bank']?.toString();
    Branch = json['Branch']?.toString();
    Accno = json['Accno']?.toString();
    IFSC = json['IFSC']?.toString();
    City = json['City']?.toString();
    State = json['State']?.toString();
    StateId = json['StateId']?.toString();
    CBStatus = json['CBStatus']?.toString();
    UpdatedOn = json['UpdatedOn']?.toString();
    UpdatedBy = json['UpdatedBy']?.toString();
    BankImage = json['BankImage']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['CBId'] = CBId;
    data['Bank'] = Bank;
    data['Branch'] = Branch;
    data['Accno'] = Accno;
    data['IFSC'] = IFSC;
    data['City'] = City;
    data['State'] = State;
    data['StateId'] = StateId;
    data['CBStatus'] = CBStatus;
    data['UpdatedOn'] = UpdatedOn;
    data['UpdatedBy'] = UpdatedBy;
    data['BankImage'] = BankImage;
    data['Msg'] = Msg;
    return data;
  }
}

class AddFundInpurModelGetDropDownpayout {
/*
{
  "Text": "Cash Deposits",
  "Value": "1",
  "Msg": "Success"
}
*/

  String? Text;
  String? Value;
  String? Msg;

  AddFundInpurModelGetDropDownpayout({
    this.Text,
    this.Value,
    this.Msg,
  });
  AddFundInpurModelGetDropDownpayout.fromJson(Map<String, dynamic> json) {
    Text = json['Text']?.toString();
    Value = json['Value']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Text'] = Text;
    data['Value'] = Value;
    data['Msg'] = Msg;
    return data;
  }
}

// class AddFundInpurModelGetDropDownstateout {
// /*
// {
//   "Text": "Andaman and Nicobar Islands",
//   "Value": "1",
//   "Msg": "Success"
// }
// */
//
//   String? Text;
//   String? Value;
//   String? Msg;
//
//   AddFundInpurModelGetDropDownstateout({
//     this.Text,
//     this.Value,
//     this.Msg,
//   });
//   AddFundInpurModelGetDropDownstateout.fromJson(Map<String, dynamic> json) {
//     Text = json['Text']?.toString();
//     Value = json['Value']?.toString();
//     Msg = json['Msg']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['Text'] = Text;
//     data['Value'] = Value;
//     data['Msg'] = Msg;
//     return data;
//   }
// }

class AddFundInpurModel {
/*
{
  "GetDropDownstateout": [
    {
      "Text": "Andaman and Nicobar Islands",
      "Value": "1",
      "Msg": "Success"
    }
  ],
  "GetDropDownpayout": [
    {
      "Text": "Cash Deposits",
      "Value": "1",
      "Msg": "Success"
    }
  ],
  "CompanyBanks": [
    {
      "CBId": "4",
      "Bank": "Bandhan Bank",
      "Branch": "DALHOUSIE",
      "Accno": "10190000882112",
      "IFSC": "BDBL0001625",
      "City": "Kolkata",
      "State": "West Bengal",
      "StateId": "35",
      "CBStatus": "0",
      "UpdatedOn": "31 Mar 2021",
      "UpdatedBy": "admin - USER001",
      "BankImage": "",
      "Msg": "SUCCESS"
    }
  ],
  "Msg": "Succ",
  "Message": "Success",
  "Balance": "9600.20"
}
*/

  List<StateModel?>? GetDropDownstateout;
  List<AddFundInpurModelGetDropDownpayout?>? GetDropDownpayout;
  List<AddFundInpurModelCompanyBanks?>? CompanyBanks;
  String? Msg;
  String? Message;
  String? Balance;

  AddFundInpurModel({
    this.GetDropDownstateout,
    this.GetDropDownpayout,
    this.CompanyBanks,
    this.Msg,
    this.Message,
    this.Balance,
  });
  AddFundInpurModel.fromJson(Map<String, dynamic> json) {
    if (json['GetDropDownstateout'] != null) {
      final v = json['GetDropDownstateout'];
      final arr0 = <StateModel>[];
      v.forEach((v) {
        arr0.add(StateModel.stateJson1(v));
      });
      GetDropDownstateout = arr0;
    }
    if (json['GetDropDownpayout'] != null) {
      final v = json['GetDropDownpayout'];
      final arr0 = <AddFundInpurModelGetDropDownpayout>[];
      v.forEach((v) {
        arr0.add(AddFundInpurModelGetDropDownpayout.fromJson(v));
      });
      GetDropDownpayout = arr0;
    }
    if (json['CompanyBanks'] != null) {
      final v = json['CompanyBanks'];
      final arr0 = <AddFundInpurModelCompanyBanks>[];
      v.forEach((v) {
        arr0.add(AddFundInpurModelCompanyBanks.fromJson(v));
      });
      CompanyBanks = arr0;
    }
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    Balance = json['Balance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (GetDropDownstateout != null) {
      final v = GetDropDownstateout;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['GetDropDownstateout'] = arr0;
    }
    if (GetDropDownpayout != null) {
      final v = GetDropDownpayout;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['GetDropDownpayout'] = arr0;
    }
    if (CompanyBanks != null) {
      final v = CompanyBanks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['CompanyBanks'] = arr0;
    }
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['Balance'] = Balance;
    return data;
  }
}
