///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartItemModel {
/*
{
  "Msg": "SUCCESS",
  "Message": null,
  "result": "SUCCESS",
  "Pid": "2",
  "Pcode": "PRD0001",
  "PName": "Renatus Nova",
  "Qty": "1",
  "MRP": "1794.00",
  "DP": "1350.00",
  "TotalMRP": "1794.00",
  "TotalDP": "1350.00",
  "PV": "16.00",
  "TotPV": "16.00",
  "TotBV": "16.00",
  "UQID": "2TNXALEDS1TEAOI49LWK8R4U0MKS9X",
  "PrdWeight": "100.0000"
}
*/

  String? Msg;
  String? Message;
  String? result;
  String? Pid;
  String? Pcode;
  String? PName;
  String? Qty;
  String? MRP;
  String? DP;
  String? TotalMRP;
  String? TotalDP;
  String? PV;
  String? TotPV;
  String? TotBV;
  String? UQID;
  String? PrdWeight;

  CartItemModel({
    this.Msg,
    this.Message,
    this.result,
    this.Pid,
    this.Pcode,
    this.PName,
    this.Qty,
    this.MRP,
    this.DP,
    this.TotalMRP,
    this.TotalDP,
    this.PV,
    this.TotPV,
    this.TotBV,
    this.UQID,
    this.PrdWeight,
  });
  CartItemModel.fromJson(Map<String, dynamic> json) {
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    result = json['result']?.toString();
    Pid = json['Pid']?.toString();
    Pcode = json['Pcode']?.toString();
    PName = json['PName']?.toString();
    Qty = json['Qty']?.toString();
    MRP = json['MRP']?.toString();
    DP = json['DP']?.toString();
    TotalMRP = json['TotalMRP']?.toString();
    TotalDP = json['TotalDP']?.toString();
    PV = json['PV']?.toString();
    TotPV = json['TotPV']?.toString();
    TotBV = json['TotBV']?.toString();
    UQID = json['UQID']?.toString();
    PrdWeight = json['PrdWeight']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['result'] = result;
    data['Pid'] = Pid;
    data['Pcode'] = Pcode;
    data['PName'] = PName;
    data['Qty'] = Qty;
    data['MRP'] = MRP;
    data['DP'] = DP;
    data['TotalMRP'] = TotalMRP;
    data['TotalDP'] = TotalDP;
    data['PV'] = PV;
    data['TotPV'] = TotPV;
    data['TotBV'] = TotBV;
    data['UQID'] = UQID;
    data['PrdWeight'] = PrdWeight;
    return data;
  }
}
