///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardModelMemberDetals {
/*
{
  "Regid": null,
  "Idno": null,
  "Name": null,
  "SelfSV": null,
  "FSV": null,
  "RSV": null,
  "TotalSV": null,
  "SchFrom": null,
  "Schto": null,
  "Team": "Team 1 ( IRD10000002 )",
  "TD_PendingCnt": "0",
  "TD_ActiveCnt": "0",
  "TD_CC": "0.00",
  "CC_PendingCnt": "2",
  "CC_ActiveCnt": "1",
  "CC_CC": "102.00",
  "msg": "SUCCESS"
}
*/

  String? Regid;
  String? Idno;
  String? Name;
  String? SelfSV;
  String? FSV;
  String? RSV;
  String? TotalSV;
  String? SchFrom;
  String? Schto;
  String? Team;
  String? TDPendingCnt;
  String? TDActiveCnt;
  String? TDCC;
  String? CCPendingCnt;
  String? CCActiveCnt;
  String? CCCC;
  String? msg;

  DashboardModelMemberDetals({
    this.Regid,
    this.Idno,
    this.Name,
    this.SelfSV,
    this.FSV,
    this.RSV,
    this.TotalSV,
    this.SchFrom,
    this.Schto,
    this.Team,
    this.TDPendingCnt,
    this.TDActiveCnt,
    this.TDCC,
    this.CCPendingCnt,
    this.CCActiveCnt,
    this.CCCC,
    this.msg,
  });
  DashboardModelMemberDetals.fromJson(Map<String, dynamic> json) {
    Regid = json['Regid']?.toString();
    Idno = json['Idno']?.toString();
    Name = json['Name']?.toString();
    SelfSV = json['SelfSV']?.toString();
    FSV = json['FSV']?.toString();
    RSV = json['RSV']?.toString();
    TotalSV = json['TotalSV']?.toString();
    SchFrom = json['SchFrom']?.toString();
    Schto = json['Schto']?.toString();
    Team = json['Team']?.toString();
    TDPendingCnt = json['TD_PendingCnt']?.toString();
    TDActiveCnt = json['TD_ActiveCnt']?.toString();
    TDCC = json['TD_CC']?.toString();
    CCPendingCnt = json['CC_PendingCnt']?.toString();
    CCActiveCnt = json['CC_ActiveCnt']?.toString();
    CCCC = json['CC_CC']?.toString();
    msg = json['msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Regid'] = Regid;
    data['Idno'] = Idno;
    data['Name'] = Name;
    data['SelfSV'] = SelfSV;
    data['FSV'] = FSV;
    data['RSV'] = RSV;
    data['TotalSV'] = TotalSV;
    data['SchFrom'] = SchFrom;
    data['Schto'] = Schto;
    data['Team'] = Team;
    data['TD_PendingCnt'] = TDPendingCnt;
    data['TD_ActiveCnt'] = TDActiveCnt;
    data['TD_CC'] = TDCC;
    data['CC_PendingCnt'] = CCPendingCnt;
    data['CC_ActiveCnt'] = CCActiveCnt;
    data['CC_CC'] = CCCC;
    data['msg'] = msg;
    return data;
  }
}

class DashboardModelProfiledetals {
/*
{
  "Name": "Proprietor  Proprietor",
  "idno": "IRD10000001",
  "sprcnt": "4",
  "Mobile": "9111111111",
  "Email": "Test@ss.com",
  "pansts": "Approved",
  "banksts": "Pending",
  "aadharsts": "Not Uploaded",
  "sprname": "--",
  "joindate": "31 Dec 2009",
  "stsdate": "31 Dec 2009",
  "mstatus": "Active",
  "msg": "SUCCESS",
  "GSTStatus": "Not Uploaded",
  "SponsorID": "--",
  "ProfilePic": "NoImage.jpg",
  "IDProofSts": "Not Uploaded",
  "EWalletBalance": "2840.00",
  "PackageName": "4 %",
  "PackageAmount": "3098.0000",
  "PackageDate": "03 Feb 2018",
  "BirthdayMsg": "",
  "NetAmt": "0.00",
  "RankName": "IRD",
  "Accumulative_Rank": "Director 1000",
  "LastClosing_Rank": "IRD",
  "ProcessedUpto": "Sep 13 2021  4:00AM",
  "BF_L_CC": "0.00",
  "BF_R_CC": "0.00",
  "T_BF_CC_L_CC": "0.00",
  "T_BF_CC_R_CC": "0.00",
  "Matched_CC": "0.0000"
}
*/

  String? Name;
  String? idno;
  String? sprcnt;
  String? Mobile;
  String? Email;
  String? pansts;
  String? banksts;
  String? aadharsts;
  String? sprname;
  String? joindate;
  String? stsdate;
  String? mstatus;
  String? msg;
  String? GSTStatus;
  String? SponsorID;
  String? ProfilePic;
  String? IDProofSts;
  String? EWalletBalance;
  String? PackageName;
  String? PackageAmount;
  String? PackageDate;
  String? BirthdayMsg;
  String? NetAmt;
  String? RankName;
  String? AccumulativeRank;
  String? LastClosingRank;
  String? ProcessedUpto;
  String? BFLCC;
  String? BFRCC;
  String? TBFCCLCC;
  String? TBFCCRCC;
  String? MatchedCC;

  DashboardModelProfiledetals({
    this.Name,
    this.idno,
    this.sprcnt,
    this.Mobile,
    this.Email,
    this.pansts,
    this.banksts,
    this.aadharsts,
    this.sprname,
    this.joindate,
    this.stsdate,
    this.mstatus,
    this.msg,
    this.GSTStatus,
    this.SponsorID,
    this.ProfilePic,
    this.IDProofSts,
    this.EWalletBalance,
    this.PackageName,
    this.PackageAmount,
    this.PackageDate,
    this.BirthdayMsg,
    this.NetAmt,
    this.RankName,
    this.AccumulativeRank,
    this.LastClosingRank,
    this.ProcessedUpto,
    this.BFLCC,
    this.BFRCC,
    this.TBFCCLCC,
    this.TBFCCRCC,
    this.MatchedCC,
  });
  DashboardModelProfiledetals.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    idno = json['idno']?.toString();
    sprcnt = json['sprcnt']?.toString();
    Mobile = json['Mobile']?.toString();
    Email = json['Email']?.toString();
    pansts = json['pansts']?.toString();
    banksts = json['banksts']?.toString();
    aadharsts = json['aadharsts']?.toString();
    sprname = json['sprname']?.toString();
    joindate = json['joindate']?.toString();
    stsdate = json['stsdate']?.toString();
    mstatus = json['mstatus']?.toString();
    msg = json['msg']?.toString();
    GSTStatus = json['GSTStatus']?.toString();
    SponsorID = json['SponsorID']?.toString();
    ProfilePic = json['ProfilePic']?.toString();
    IDProofSts = json['IDProofSts']?.toString();
    EWalletBalance = json['EWalletBalance']?.toString();
    PackageName = json['PackageName']?.toString();
    PackageAmount = json['PackageAmount']?.toString();
    PackageDate = json['PackageDate']?.toString();
    BirthdayMsg = json['BirthdayMsg']?.toString();
    NetAmt = json['NetAmt']?.toString();
    RankName = json['RankName']?.toString();
    AccumulativeRank = json['Accumulative_Rank']?.toString();
    LastClosingRank = json['LastClosing_Rank']?.toString();
    ProcessedUpto = json['ProcessedUpto']?.toString();
    BFLCC = json['BF_L_CC']?.toString();
    BFRCC = json['BF_R_CC']?.toString();
    TBFCCLCC = json['T_BF_CC_L_CC']?.toString();
    TBFCCRCC = json['T_BF_CC_R_CC']?.toString();
    MatchedCC = json['Matched_CC']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['idno'] = idno;
    data['sprcnt'] = sprcnt;
    data['Mobile'] = Mobile;
    data['Email'] = Email;
    data['pansts'] = pansts;
    data['banksts'] = banksts;
    data['aadharsts'] = aadharsts;
    data['sprname'] = sprname;
    data['joindate'] = joindate;
    data['stsdate'] = stsdate;
    data['mstatus'] = mstatus;
    data['msg'] = msg;
    data['GSTStatus'] = GSTStatus;
    data['SponsorID'] = SponsorID;
    data['ProfilePic'] = ProfilePic;
    data['IDProofSts'] = IDProofSts;
    data['EWalletBalance'] = EWalletBalance;
    data['PackageName'] = PackageName;
    data['PackageAmount'] = PackageAmount;
    data['PackageDate'] = PackageDate;
    data['BirthdayMsg'] = BirthdayMsg;
    data['NetAmt'] = NetAmt;
    data['RankName'] = RankName;
    data['Accumulative_Rank'] = AccumulativeRank;
    data['LastClosing_Rank'] = LastClosingRank;
    data['ProcessedUpto'] = ProcessedUpto;
    data['BF_L_CC'] = BFLCC;
    data['BF_R_CC'] = BFRCC;
    data['T_BF_CC_L_CC'] = TBFCCLCC;
    data['T_BF_CC_R_CC'] = TBFCCRCC;
    data['Matched_CC'] = MatchedCC;
    return data;
  }
}

class DashboardModel {
/*
{
  "Profiledetals": [
    {
      "Name": "Proprietor  Proprietor",
      "idno": "IRD10000001",
      "sprcnt": "4",
      "Mobile": "9111111111",
      "Email": "Test@ss.com",
      "pansts": "Approved",
      "banksts": "Pending",
      "aadharsts": "Not Uploaded",
      "sprname": "--",
      "joindate": "31 Dec 2009",
      "stsdate": "31 Dec 2009",
      "mstatus": "Active",
      "msg": "SUCCESS",
      "GSTStatus": "Not Uploaded",
      "SponsorID": "--",
      "ProfilePic": "NoImage.jpg",
      "IDProofSts": "Not Uploaded",
      "EWalletBalance": "2840.00",
      "PackageName": "4 %",
      "PackageAmount": "3098.0000",
      "PackageDate": "03 Feb 2018",
      "BirthdayMsg": "",
      "NetAmt": "0.00",
      "RankName": "IRD",
      "Accumulative_Rank": "Director 1000",
      "LastClosing_Rank": "IRD",
      "ProcessedUpto": "Sep 13 2021  4:00AM",
      "BF_L_CC": "0.00",
      "BF_R_CC": "0.00",
      "T_BF_CC_L_CC": "0.00",
      "T_BF_CC_R_CC": "0.00",
      "Matched_CC": "0.0000"
    }
  ],
  "memberDetals": [
    {
      "Regid": null,
      "Idno": null,
      "Name": null,
      "SelfSV": null,
      "FSV": null,
      "RSV": null,
      "TotalSV": null,
      "SchFrom": null,
      "Schto": null,
      "Team": "Team 1 ( IRD10000002 )",
      "TD_PendingCnt": "0",
      "TD_ActiveCnt": "0",
      "TD_CC": "0.00",
      "CC_PendingCnt": "2",
      "CC_ActiveCnt": "1",
      "CC_CC": "102.00",
      "msg": "SUCCESS"
    }
  ],
  "Eventsdetails": [
    null
  ],
  "NewProductsOffer": [
    null
  ],
  "Msg": null,
  "Message": null,
  "Result": null
}
*/

  List<DashboardModelProfiledetals?>? Profiledetals;
  List<DashboardModelMemberDetals?>? memberDetals;
  String? Msg;
  String? Message;
  String? Result;

  DashboardModel({
    this.Profiledetals,
    this.memberDetals,
    this.Msg,
    this.Message,
    this.Result,
  });
  DashboardModel.fromJson(Map<String, dynamic> json) {
    if (json['Profiledetals'] != null) {
      final v = json['Profiledetals'];
      final arr0 = <DashboardModelProfiledetals>[];
      v.forEach((v) {
        arr0.add(DashboardModelProfiledetals.fromJson(v));
      });
      Profiledetals = arr0;
    }
    if (json['memberDetals'] != null) {
      final v = json['memberDetals'];
      final arr0 = <DashboardModelMemberDetals>[];
      v.forEach((v) {
        arr0.add(DashboardModelMemberDetals.fromJson(v));
      });
      memberDetals = arr0;
    }
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    Result = json['Result']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Profiledetals != null) {
      final v = Profiledetals;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Profiledetals'] = arr0;
    }
    if (memberDetals != null) {
      final v = memberDetals;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['memberDetals'] = arr0;
    }
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['Result'] = Result;
    return data;
    }
}
