///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeDataProducts {
/*
{
  "ProductID": 2,
  "ProductName": "Renatus Nova",
  "MRP": 1794,
  "DP": 1350,
  "PV": 16,
  "ProductImage": "FileUpload/ProductImages/nrfklK7B5y_Thumb.jpg"
} 
*/

  int? ProductID;
  String? ProductName;
  int? MRP;
  int? DP;
  int? PV;
  String? ProductImage;
  String? DetailDescription;

  HomeDataProducts({
    this.ProductID,
    this.ProductName,
    this.MRP,
    this.DP,
    this.PV,
    this.ProductImage,
    this.DetailDescription,
  });
  HomeDataProducts.fromJson(Map<String, dynamic> json) {
    ProductID = json['ProductID']?.toInt();
    ProductName = json['ProductName']?.toString();
    MRP = json['MRP']?.toInt();
    DP = json['DP']?.toInt();
    PV = json['PV']?.toInt();
    ProductImage = json['ProductImage']?.toString();
    DetailDescription = json['DetailDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ProductID'] = ProductID;
    data['ProductName'] = ProductName;
    data['MRP'] = MRP;
    data['DP'] = DP;
    data['PV'] = PV;
    data['ProductImage'] = ProductImage;
    data['DetailDescription'] = DetailDescription;
    return data;
  }
}

class HomeDataBanners {
/*
{
  "BannerUrl": "FileUpload/HomePageBanners/Banner1.png"
} 
*/

  String? BannerUrl;

  HomeDataBanners({
    this.BannerUrl,
  });
  HomeDataBanners.fromJson(Map<String, dynamic> json) {
    BannerUrl = json['BannerUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['BannerUrl'] = BannerUrl;
    return data;
  }
}

class HomeData {
/*
{
  "Banners": [
    {
      "BannerUrl": "FileUpload/HomePageBanners/Banner1.png"
    }
  ],
  "Products": [
    {
      "ProductID": 2,
      "ProductName": "Renatus Nova",
      "MRP": 1794,
      "DP": 1350,
      "PV": 16,
      "ProductImage": "FileUpload/ProductImages/nrfklK7B5y_Thumb.jpg"
    }
  ]
} 
*/

  List<HomeDataBanners?>? Banners;
  List<HomeDataProducts?>? Products;

  HomeData({
    this.Banners,
    this.Products,
  });
  HomeData.fromJson(Map<String, dynamic> json) {
    if (json['Banners'] != null) {
      final v = json['Banners'];
      final arr0 = <HomeDataBanners>[];
      v.forEach((v) {
        arr0.add(HomeDataBanners.fromJson(v));
      });
      Banners = arr0;
    }
    if (json['Products'] != null) {
      final v = json['Products'];
      final arr0 = <HomeDataProducts>[];
      v.forEach((v) {
        arr0.add(HomeDataProducts.fromJson(v));
      });
      Products = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Banners != null) {
      final v = Banners;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Banners'] = arr0;
    }
    if (Products != null) {
      final v = Products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Products'] = arr0;
    }
    return data;
  }
}
