///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyReferralsModel {
/*
{
  "Idno": "IRD10000002",
  "Name": "Renatus_3  Renatus_3",
  "CityName": "Hyderabad",
  "StateName": "Tripura",
  "Mobile": "9111111111",
  "Mstatus": "Active",
  "JoinDate": "14 Sep 2018",
  "Placement": "Left",
  "Msg": "SUCCESS"
}
*/

  String? Idno;
  String? Name;
  String? CityName;
  String? StateName;
  String? Mobile;
  String? Mstatus;
  String? JoinDate;
  String? Placement;
  String? Msg;

  MyReferralsModel({
    this.Idno,
    this.Name,
    this.CityName,
    this.StateName,
    this.Mobile,
    this.Mstatus,
    this.JoinDate,
    this.Placement,
    this.Msg,
  });
  MyReferralsModel.fromJson(Map<String, dynamic> json) {
    Idno = json['Idno']?.toString();
    Name = json['Name']?.toString();
    CityName = json['CityName']?.toString();
    StateName = json['StateName']?.toString();
    Mobile = json['Mobile']?.toString();
    Mstatus = json['Mstatus']?.toString();
    JoinDate = json['JoinDate']?.toString();
    Placement = json['Placement']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Idno'] = Idno;
    data['Name'] = Name;
    data['CityName'] = CityName;
    data['StateName'] = StateName;
    data['Mobile'] = Mobile;
    data['Mstatus'] = Mstatus;
    data['JoinDate'] = JoinDate;
    data['Placement'] = Placement;
    data['Msg'] = Msg;
    return data;
  }
}
