///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderStatusModel {
/*
{
  "result": "Invalid Transaction Password",
  "Msg": "FAILED",
  "Message": null,
  "BillNo": null,
  "Email": null,
  "Mobile": null
}
*/

  String? result;
  String? Msg;
  String? Message;
  String? BillNo;
  String? Email;
  String? Mobile;

  OrderStatusModel({
    this.result,
    this.Msg,
    this.Message,
    this.BillNo,
    this.Email,
    this.Mobile,
  });
  OrderStatusModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    BillNo = json['BillNo']?.toString();
    Email = json['Email']?.toString();
    Mobile = json['Mobile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['BillNo'] = BillNo;
    data['Email'] = Email;
    data['Mobile'] = Mobile;
    return data;
  }
}
