///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderProductsModelOrderProducts {
/*
{
  "Msg": "SUCCESS",
  "Message": null,
  "Pid": "2",
  "Pcode": "PRD0001",
  "Name": "Renatus Nova",
  "MRP": "1794.0000",
  "DP": "1350.0000",
  "Qty": "1",
  "PV": "16.0000",
  "ThumbImage": "http://staging.renatuswellness.net/../fileUpload/ProductImages/nrfklK7B5y_Thumb.jpg",
  "ShowQty": "No",
  "AvailQty": "0"
}
*/

  String? Msg;
  String? Message;
  String? Pid;
  String? Pcode;
  String? Name;
  String? MRP;
  String? DP;
  String? Qty;
  String? PV;
  String? ThumbImage;
  String? ShowQty;
  String? AvailQty;

  OrderProductsModelOrderProducts({
    this.Msg,
    this.Message,
    this.Pid,
    this.Pcode,
    this.Name,
    this.MRP,
    this.DP,
    this.Qty,
    this.PV,
    this.ThumbImage,
    this.ShowQty,
    this.AvailQty,
  });
  OrderProductsModelOrderProducts.fromJson(Map<String, dynamic> json) {
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    Pid = json['Pid']?.toString();
    Pcode = json['Pcode']?.toString();
    Name = json['Name']?.toString();
    MRP = json['MRP']?.toString();
    DP = json['DP']?.toString();
    Qty = json['Qty']?.toString();
    PV = json['PV']?.toString();
    ThumbImage = json['ThumbImage']?.toString();
    ShowQty = json['ShowQty']?.toString();
    AvailQty = json['AvailQty']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['Pid'] = Pid;
    data['Pcode'] = Pcode;
    data['Name'] = Name;
    data['MRP'] = MRP;
    data['DP'] = DP;
    data['Qty'] = Qty;
    data['PV'] = PV;
    data['ThumbImage'] = ThumbImage;
    data['ShowQty'] = ShowQty;
    data['AvailQty'] = AvailQty;
    return data;
  }
}

class OrderProductsModel {
/*
{
  "OrderProducts": [
    {
      "Msg": "SUCCESS",
      "Message": null,
      "Pid": "2",
      "Pcode": "PRD0001",
      "Name": "Renatus Nova",
      "MRP": "1794.0000",
      "DP": "1350.0000",
      "Qty": "1",
      "PV": "16.0000",
      "ThumbImage": "http://staging.renatuswellness.net/../fileUpload/ProductImages/nrfklK7B5y_Thumb.jpg",
      "ShowQty": "No",
      "AvailQty": "0"
    }
  ],
  "Msg": null,
  "Message": null
}
*/

  List<OrderProductsModelOrderProducts?>? OrderProducts;
  String? Msg;
  String? Message;

  OrderProductsModel({
    this.OrderProducts,
    this.Msg,
    this.Message,
  });
  OrderProductsModel.fromJson(Map<String, dynamic> json) {
    if (json['OrderProducts'] != null) {
      final v = json['OrderProducts'];
      final arr0 = <OrderProductsModelOrderProducts>[];
      v.forEach((v) {
        arr0.add(OrderProductsModelOrderProducts.fromJson(v));
      });
      OrderProducts = arr0;
    }
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (OrderProducts != null) {
      final v = OrderProducts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['OrderProducts'] = arr0;
    }
    data['Msg'] = Msg;
    data['Message'] = Message;
    return data;
  }
}
