///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderBillAddressModel {
/*
{
  "Msg": "SUCCESS",
  "Message": "success",
  "regid": "1",
  "Name": "Proprietor  Proprietor",
  "Address": "Pune , Pune",
  "StateId": "21",
  "StateName": "Maharashtra",
  "District": "Pune",
  "City": "Pune",
  "PinCode": "500013",
  "Mobile": "91XXXXXX11",
  "EMail": "Test@ss.com",
  "MStatus": "1"
}
*/

  String? Msg;
  String? Message;
  String? regid;
  String? Name;
  String? Address;
  String? StateId;
  String? StateName;
  String? District;
  String? City;
  String? PinCode;
  String? Mobile;
  String? EMail;
  String? MStatus;

  OrderBillAddressModel({
    this.Msg,
    this.Message,
    this.regid,
    this.Name,
    this.Address,
    this.StateId,
    this.StateName,
    this.District,
    this.City,
    this.PinCode,
    this.Mobile,
    this.EMail,
    this.MStatus,
  });
  OrderBillAddressModel.fromJson(Map<String, dynamic> json) {
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
    regid = json['regid']?.toString();
    Name = json['Name']?.toString();
    Address = json['Address']?.toString();
    StateId = json['StateId']?.toString();
    StateName = json['StateName']?.toString();
    District = json['District']?.toString();
    City = json['City']?.toString();
    PinCode = json['PinCode']?.toString();
    Mobile = json['Mobile']?.toString();
    EMail = json['EMail']?.toString();
    MStatus = json['MStatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Msg'] = Msg;
    data['Message'] = Message;
    data['regid'] = regid;
    data['Name'] = Name;
    data['Address'] = Address;
    data['StateId'] = StateId;
    data['StateName'] = StateName;
    data['District'] = District;
    data['City'] = City;
    data['PinCode'] = PinCode;
    data['Mobile'] = Mobile;
    data['EMail'] = EMail;
    data['MStatus'] = MStatus;
    return data;
  }
}
