///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OnholdReportModel {
/*
{
  "Idno": "IRD87685797",
  "RegId": "793384",
  "Name": "MITHLESH  KUMARI",
  "amt": "1392.00",
  "Status": "Dual Team TurnOver Bonus",
  "remarks": "PAN NOT AVAILABLE",
  "Payno": "107",
  "ClosingDate": "29 Aug 2021 - 11 Oct 2021",
  "Msg": "SUCCESS",
  "Desgno": "1",
  "DesgName": "Associate",
  "MPer": "8.0000",
  "MatchedCC": "290.0000"
}
*/

  String? Idno;
  String? RegId;
  String? Name;
  String? amt;
  String? Status;
  String? remarks;
  String? Payno;
  String? ClosingDate;
  String? Msg;
  String? Desgno;
  String? DesgName;
  String? MPer;
  String? MatchedCC;

  OnholdReportModel({
    this.Idno,
    this.RegId,
    this.Name,
    this.amt,
    this.Status,
    this.remarks,
    this.Payno,
    this.ClosingDate,
    this.Msg,
    this.Desgno,
    this.DesgName,
    this.MPer,
    this.MatchedCC,
  });
  OnholdReportModel.fromJson(Map<String, dynamic> json) {
    Idno = json['Idno']?.toString();
    RegId = json['RegId']?.toString();
    Name = json['Name']?.toString();
    amt = json['amt']?.toString();
    Status = json['Status']?.toString();
    remarks = json['remarks']?.toString();
    Payno = json['Payno']?.toString();
    ClosingDate = json['ClosingDate']?.toString();
    Msg = json['Msg']?.toString();
    Desgno = json['Desgno']?.toString();
    DesgName = json['DesgName']?.toString();
    MPer = json['MPer']?.toString();
    MatchedCC = json['MatchedCC']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Idno'] = Idno;
    data['RegId'] = RegId;
    data['Name'] = Name;
    data['amt'] = amt;
    data['Status'] = Status;
    data['remarks'] = remarks;
    data['Payno'] = Payno;
    data['ClosingDate'] = ClosingDate;
    data['Msg'] = Msg;
    data['Desgno'] = Desgno;
    data['DesgName'] = DesgName;
    data['MPer'] = MPer;
    data['MatchedCC'] = MatchedCC;
    return data;
  }
}
