///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileModelMemberProfile {
/*
{
  "Regid": "1",
  "Memdate": "31 Dec 2009",
  "Sponsor": "",
  "SponsorName": "  ",
  "Idno": "IRD10000001",
  "Name": "Proprietor  Proprietor",
  "Address1": "Pune , Pune",
  "Address2": "",
  "City": "Pune",
  "State": "Maharashtra",
  "StateID": "21",
  "PinCode": "500013",
  "Mobile": "9111111111",
  "EMail": "Test@ss.com",
  "Panno": "ABCDE1235R",
  "gstin": "Not Available",
  "PayeeName": "renatus",
  "Bank": "HDFC BANK",
  "Accno": "111222333",
  "Branch": "PUNE - NANA PETH",
  "Ifscode": "HDFC0000633",
  "stsid": "1",
  "Status": "Active",
  "DOB": "01/09/1919",
  "Nominee": "",
  "Relation": "",
  "Msg": "SUCCESS"
}
*/

  String? Regid;
  String? Memdate;
  String? Sponsor;
  String? SponsorName;
  String? Idno;
  String? Name;
  String? Address1;
  String? Address2;
  String? City;
  String? State;
  String? StateID;
  String? PinCode;
  String? Mobile;
  String? EMail;
  String? Panno;
  String? gstin;
  String? PayeeName;
  String? Bank;
  String? Accno;
  String? Branch;
  String? Ifscode;
  String? stsid;
  String? Status;
  String? DOB;
  String? Nominee;
  String? Relation;
  String? Msg;

  ProfileModelMemberProfile({
    this.Regid,
    this.Memdate,
    this.Sponsor,
    this.SponsorName,
    this.Idno,
    this.Name,
    this.Address1,
    this.Address2,
    this.City,
    this.State,
    this.StateID,
    this.PinCode,
    this.Mobile,
    this.EMail,
    this.Panno,
    this.gstin,
    this.PayeeName,
    this.Bank,
    this.Accno,
    this.Branch,
    this.Ifscode,
    this.stsid,
    this.Status,
    this.DOB,
    this.Nominee,
    this.Relation,
    this.Msg,
  });
  ProfileModelMemberProfile.fromJson(Map<String, dynamic> json) {
    Regid = json['Regid']?.toString();
    Memdate = json['Memdate']?.toString();
    Sponsor = json['Sponsor']?.toString();
    SponsorName = json['SponsorName']?.toString();
    Idno = json['Idno']?.toString();
    Name = json['Name']?.toString();
    Address1 = json['Address1']?.toString();
    Address2 = json['Address2']?.toString();
    City = json['City']?.toString();
    State = json['State']?.toString();
    StateID = json['StateID']?.toString();
    PinCode = json['PinCode']?.toString();
    Mobile = json['Mobile']?.toString();
    EMail = json['EMail']?.toString();
    Panno = json['Panno']?.toString();
    gstin = json['gstin']?.toString();
    PayeeName = json['PayeeName']?.toString();
    Bank = json['Bank']?.toString();
    Accno = json['Accno']?.toString();
    Branch = json['Branch']?.toString();
    Ifscode = json['Ifscode']?.toString();
    stsid = json['stsid']?.toString();
    Status = json['Status']?.toString();
    DOB = json['DOB']?.toString();
    Nominee = json['Nominee']?.toString();
    Relation = json['Relation']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Regid'] = Regid;
    data['Memdate'] = Memdate;
    data['Sponsor'] = Sponsor;
    data['SponsorName'] = SponsorName;
    data['Idno'] = Idno;
    data['Name'] = Name;
    data['Address1'] = Address1;
    data['Address2'] = Address2;
    data['City'] = City;
    data['State'] = State;
    data['StateID'] = StateID;
    data['PinCode'] = PinCode;
    data['Mobile'] = Mobile;
    data['EMail'] = EMail;
    data['Panno'] = Panno;
    data['gstin'] = gstin;
    data['PayeeName'] = PayeeName;
    data['Bank'] = Bank;
    data['Accno'] = Accno;
    data['Branch'] = Branch;
    data['Ifscode'] = Ifscode;
    data['stsid'] = stsid;
    data['Status'] = Status;
    data['DOB'] = DOB;
    data['Nominee'] = Nominee;
    data['Relation'] = Relation;
    data['Msg'] = Msg;
    return data;
  }
}

class ProfileModel {
/*
{
  "MemberProfile": [
    {
      "Regid": "1",
      "Memdate": "31 Dec 2009",
      "Sponsor": "",
      "SponsorName": "  ",
      "Idno": "IRD10000001",
      "Name": "Proprietor  Proprietor",
      "Address1": "Pune , Pune",
      "Address2": "",
      "City": "Pune",
      "State": "Maharashtra",
      "StateID": "21",
      "PinCode": "500013",
      "Mobile": "9111111111",
      "EMail": "Test@ss.com",
      "Panno": "ABCDE1235R",
      "gstin": "Not Available",
      "PayeeName": "renatus",
      "Bank": "HDFC BANK",
      "Accno": "111222333",
      "Branch": "PUNE - NANA PETH",
      "Ifscode": "HDFC0000633",
      "stsid": "1",
      "Status": "Active",
      "DOB": "01/09/1919",
      "Nominee": "",
      "Relation": "",
      "Msg": "SUCCESS"
    }
  ],
  "Msg": null,
  "Message": null
}
*/

  List<ProfileModelMemberProfile?>? MemberProfile;
  String? Msg;
  String? Message;

  ProfileModel({
    this.MemberProfile,
    this.Msg,
    this.Message,
  });
  ProfileModel.fromJson(Map<String, dynamic> json) {
    if (json['MemberProfile'] != null) {
      final v = json['MemberProfile'];
      final arr0 = <ProfileModelMemberProfile>[];
      v.forEach((v) {
        arr0.add(ProfileModelMemberProfile.fromJson(v));
      });
      MemberProfile = arr0;
    }
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (MemberProfile != null) {
      final v = MemberProfile;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['MemberProfile'] = arr0;
    }
    data['Msg'] = Msg;
    data['Message'] = Message;
    return data;
  }
}
