///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SchemeOfferModel {
/*
{
  "idno": "IRD10000001",
  "Name": "Proprietor Proprietor",
  "mobile": "9111111111",
  "Address": "Pune , Pune",
  "SchemeName": "RETREAT PROGRAM 2021-22 QUADRANT I",
  "SchemeDescr": "Required 3000 CC in both team (Left & Right), all new business to be completed from 1st April 2021, Thursday to 10th July 2021, Saturday. Carry forward of previous quadrant will not be considered.",
  "LeftCC": "3000.0000",
  "RightCC": "3000.0000",
  "actualleftcc": "4903256.0000",
  "actualrightcc": "0.0000",
  "requiredleftcc": "0.0000",
  "requiredrightcc": "3000.0000",
  "Status": "NOT ACHIEVED SCHEME CLOSED",
  "ProcessedUptoDate": "Processed Up to : 12 Sep 2021",
  "Msg": "SUCCESS"
}
*/

  String? idno;
  String? Name;
  String? mobile;
  String? Address;
  String? SchemeName;
  String? SchemeDescr;
  String? LeftCC;
  String? RightCC;
  String? actualleftcc;
  String? actualrightcc;
  String? requiredleftcc;
  String? requiredrightcc;
  String? Status;
  String? ProcessedUptoDate;
  String? Msg;

  SchemeOfferModel({
    this.idno,
    this.Name,
    this.mobile,
    this.Address,
    this.SchemeName,
    this.SchemeDescr,
    this.LeftCC,
    this.RightCC,
    this.actualleftcc,
    this.actualrightcc,
    this.requiredleftcc,
    this.requiredrightcc,
    this.Status,
    this.ProcessedUptoDate,
    this.Msg,
  });
  SchemeOfferModel.fromJson(Map<String, dynamic> json) {
    idno = json['idno']?.toString();
    Name = json['Name']?.toString();
    mobile = json['mobile']?.toString();
    Address = json['Address']?.toString();
    SchemeName = json['SchemeName']?.toString();
    SchemeDescr = json['SchemeDescr']?.toString();
    LeftCC = json['LeftCC']?.toString();
    RightCC = json['RightCC']?.toString();
    actualleftcc = json['actualleftcc']?.toString();
    actualrightcc = json['actualrightcc']?.toString();
    requiredleftcc = json['requiredleftcc']?.toString();
    requiredrightcc = json['requiredrightcc']?.toString();
    Status = json['Status']?.toString();
    ProcessedUptoDate = json['ProcessedUptoDate']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idno'] = idno;
    data['Name'] = Name;
    data['mobile'] = mobile;
    data['Address'] = Address;
    data['SchemeName'] = SchemeName;
    data['SchemeDescr'] = SchemeDescr;
    data['LeftCC'] = LeftCC;
    data['RightCC'] = RightCC;
    data['actualleftcc'] = actualleftcc;
    data['actualrightcc'] = actualrightcc;
    data['requiredleftcc'] = requiredleftcc;
    data['requiredrightcc'] = requiredrightcc;
    data['Status'] = Status;
    data['ProcessedUptoDate'] = ProcessedUptoDate;
    data['Msg'] = Msg;
    return data;
  }
}
