///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TabularGenealogyModel {
/*
{
  "Msg": "SUCCESS",
  "LevelNo": "1",
  "LevelCount": "5"
}
*/

  String? Msg;
  String? LevelNo;
  String? LevelCount;

  TabularGenealogyModel({
    this.Msg,
    this.LevelNo,
    this.LevelCount,
  });
  TabularGenealogyModel.fromJson(Map<String, dynamic> json) {
    Msg = json['Msg']?.toString();
    LevelNo = json['LevelNo']?.toString();
    LevelCount = json['LevelCount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Msg'] = Msg;
    data['LevelNo'] = LevelNo;
    data['LevelCount'] = LevelCount;
    return data;
  }
}
