///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TabularCountModel {
/*
{
  "IDNo": "IRD21268894",
  "Name": "Mohit Surana",
  "City": "Bengaluru",
  "State": "Karnataka",
  "DOJ": "18 Nov 2020",
  "Sponsor": "IRD32687342",
  "Sponsorname": "Ivy Saldanha",
  "status": "Active",
  "Msg": "SUCCESS"
}
*/

  String? IDNo;
  String? Name;
  String? City;
  String? State;
  String? DOJ;
  String? Sponsor;
  String? Sponsorname;
  String? status;
  String? Msg;

  TabularCountModel({
    this.IDNo,
    this.Name,
    this.City,
    this.State,
    this.DOJ,
    this.Sponsor,
    this.Sponsorname,
    this.status,
    this.Msg,
  });
  TabularCountModel.fromJson(Map<String, dynamic> json) {
    IDNo = json['IDNo']?.toString();
    Name = json['Name']?.toString();
    City = json['City']?.toString();
    State = json['State']?.toString();
    DOJ = json['DOJ']?.toString();
    Sponsor = json['Sponsor']?.toString();
    Sponsorname = json['Sponsorname']?.toString();
    status = json['status']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['IDNo'] = IDNo;
    data['Name'] = Name;
    data['City'] = City;
    data['State'] = State;
    data['DOJ'] = DOJ;
    data['Sponsor'] = Sponsor;
    data['Sponsorname'] = Sponsorname;
    data['status'] = status;
    data['Msg'] = Msg;
    return data;
  }
}
