///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UnilevelTreeDetailsModelUniLevelTreeViewDet {
/*
{
  "regid": "2",
  "Name": "Renatus_3 Renatus_3",
  "UserID": "IRD10000002",
  "Sprcount": "1",
  "DownCnt": "1016693",
  "SelfAmt": "2160.00",
  "SelfBV": "32.00",
  "DownAmt": "2711816654.00",
  "DownBV": "37377133.00",
  "Sponsor": "IRD10000001",
  "sprname": "Proprietor Proprietor",
  "memdate": "14 Sep 2018",
  "stsdate": "14 Sep 2018",
  "StsID": "1",
  "mstatus": "Active",
  "Designation": "",
  "Mobile": "9111111111",
  "UserIDNo": "Renatus_3",
  "Message": "Success"
}
*/

  String? regid;
  String? Name;
  String? UserID;
  String? Sprcount;
  String? DownCnt;
  String? SelfAmt;
  String? SelfBV;
  String? DownAmt;
  String? DownBV;
  String? Sponsor;
  String? sprname;
  String? memdate;
  String? stsdate;
  String? StsID;
  String? mstatus;
  String? Designation;
  String? Mobile;
  String? UserIDNo;
  String? Message;

  UnilevelTreeDetailsModelUniLevelTreeViewDet({
    this.regid,
    this.Name,
    this.UserID,
    this.Sprcount,
    this.DownCnt,
    this.SelfAmt,
    this.SelfBV,
    this.DownAmt,
    this.DownBV,
    this.Sponsor,
    this.sprname,
    this.memdate,
    this.stsdate,
    this.StsID,
    this.mstatus,
    this.Designation,
    this.Mobile,
    this.UserIDNo,
    this.Message,
  });
  UnilevelTreeDetailsModelUniLevelTreeViewDet.fromJson(Map<String, dynamic> json) {
    regid = json['regid']?.toString();
    Name = json['Name']?.toString();
    UserID = json['UserID']?.toString();
    Sprcount = json['Sprcount']?.toString();
    DownCnt = json['DownCnt']?.toString();
    SelfAmt = json['SelfAmt']?.toString();
    SelfBV = json['SelfBV']?.toString();
    DownAmt = json['DownAmt']?.toString();
    DownBV = json['DownBV']?.toString();
    Sponsor = json['Sponsor']?.toString();
    sprname = json['sprname']?.toString();
    memdate = json['memdate']?.toString();
    stsdate = json['stsdate']?.toString();
    StsID = json['StsID']?.toString();
    mstatus = json['mstatus']?.toString();
    Designation = json['Designation']?.toString();
    Mobile = json['Mobile']?.toString();
    UserIDNo = json['UserIDNo']?.toString();
    Message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['regid'] = regid;
    data['Name'] = Name;
    data['UserID'] = UserID;
    data['Sprcount'] = Sprcount;
    data['DownCnt'] = DownCnt;
    data['SelfAmt'] = SelfAmt;
    data['SelfBV'] = SelfBV;
    data['DownAmt'] = DownAmt;
    data['DownBV'] = DownBV;
    data['Sponsor'] = Sponsor;
    data['sprname'] = sprname;
    data['memdate'] = memdate;
    data['stsdate'] = stsdate;
    data['StsID'] = StsID;
    data['mstatus'] = mstatus;
    data['Designation'] = Designation;
    data['Mobile'] = Mobile;
    data['UserIDNo'] = UserIDNo;
    data['Message'] = Message;
    return data;
  }
}

class UnilevelTreeDetailsModel {
/*
{
  "UniLevelTreeViewDet": [
    {
      "regid": "2",
      "Name": "Renatus_3 Renatus_3",
      "UserID": "IRD10000002",
      "Sprcount": "1",
      "DownCnt": "1016693",
      "SelfAmt": "2160.00",
      "SelfBV": "32.00",
      "DownAmt": "2711816654.00",
      "DownBV": "37377133.00",
      "Sponsor": "IRD10000001",
      "sprname": "Proprietor Proprietor",
      "memdate": "14 Sep 2018",
      "stsdate": "14 Sep 2018",
      "StsID": "1",
      "mstatus": "Active",
      "Designation": "",
      "Mobile": "9111111111",
      "UserIDNo": "Renatus_3",
      "Message": "Success"
    }
  ],
  "Result": null,
  "Msg": null,
  "Message": null
}
*/

  List<UnilevelTreeDetailsModelUniLevelTreeViewDet?>? UniLevelTreeViewDet;
  String? Result;
  String? Msg;
  String? Message;

  UnilevelTreeDetailsModel({
    this.UniLevelTreeViewDet,
    this.Result,
    this.Msg,
    this.Message,
  });
  UnilevelTreeDetailsModel.fromJson(Map<String, dynamic> json) {
    if (json['UniLevelTreeViewDet'] != null) {
      final v = json['UniLevelTreeViewDet'];
      final arr0 = <UnilevelTreeDetailsModelUniLevelTreeViewDet>[];
      v.forEach((v) {
        arr0.add(UnilevelTreeDetailsModelUniLevelTreeViewDet.fromJson(v));
      });
      UniLevelTreeViewDet = arr0;
    }
    Result = json['Result']?.toString();
    Msg = json['Msg']?.toString();
    Message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (UniLevelTreeViewDet != null) {
      final v = UniLevelTreeViewDet;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['UniLevelTreeViewDet'] = arr0;
    }
    data['Result'] = Result;
    data['Msg'] = Msg;
    data['Message'] = Message;
    return data;
  }
}
