///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EwalletSummaryRptModel {
/*
{
  "RegId": "1",
  "UserId": "IRD10000001",
  "Name": "Proprietor  Proprietor",
  "City": "Pune",
  "Mobile": "9111111111",
  "dated": "29 Nov 2021",
  "InAmt": "10000.00",
  "OutAmt": "0.00",
  "Balance": "10080.20",
  "descr": "",
  "remarks": "testing",
  "AdjustType": "ADD WALLET",
  "OpenBal": "0.00",
  "AdvType": "",
  "Msg": "SUCCESS"
}
*/

  String? RegId;
  String? UserId;
  String? Name;
  String? City;
  String? Mobile;
  String? dated;
  String? InAmt;
  String? OutAmt;
  String? Balance;
  String? descr;
  String? remarks;
  String? AdjustType;
  String? OpenBal;
  String? AdvType;
  String? Msg;

  EwalletSummaryRptModel({
    this.RegId,
    this.UserId,
    this.Name,
    this.City,
    this.Mobile,
    this.dated,
    this.InAmt,
    this.OutAmt,
    this.Balance,
    this.descr,
    this.remarks,
    this.AdjustType,
    this.OpenBal,
    this.AdvType,
    this.Msg,
  });
  EwalletSummaryRptModel.fromJson(Map<String, dynamic> json) {
    RegId = json['RegId']?.toString();
    UserId = json['UserId']?.toString();
    Name = json['Name']?.toString();
    City = json['City']?.toString();
    Mobile = json['Mobile']?.toString();
    dated = json['dated']?.toString();
    InAmt = json['InAmt']?.toString();
    OutAmt = json['OutAmt']?.toString();
    Balance = json['Balance']?.toString();
    descr = json['descr']?.toString();
    remarks = json['remarks']?.toString();
    AdjustType = json['AdjustType']?.toString();
    OpenBal = json['OpenBal']?.toString();
    AdvType = json['AdvType']?.toString();
    Msg = json['Msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['RegId'] = RegId;
    data['UserId'] = UserId;
    data['Name'] = Name;
    data['City'] = City;
    data['Mobile'] = Mobile;
    data['dated'] = dated;
    data['InAmt'] = InAmt;
    data['OutAmt'] = OutAmt;
    data['Balance'] = Balance;
    data['descr'] = descr;
    data['remarks'] = remarks;
    data['AdjustType'] = AdjustType;
    data['OpenBal'] = OpenBal;
    data['AdvType'] = AdvType;
    data['Msg'] = Msg;
    return data;
  }
}
